"""
###############################################################################
This script is used to generate an NIS Elements macro that converts the ics 
files generated by the Huyigens Deconvolution software to nd2 files with the 
proper orientation using the standard color scheme (blue,green,red,white). The script will 
add an entry in the macro file for all *cmle.ics files.
###############################################################################
Created on Thu Feb 22 07:01:07 2018
@author: Nikon Center of Excellence - Institute of Experimental Medicine
@version: Python 3 (3.5)
"""

import os
import sys
import fnmatch

#Intro
pathImageLib = os.path.dirname(sys.argv[0])#path of the script
nisMacrofile='nisMacro.mac'#name of the macro that is printed
fileList=[]#List to collect filenames for final output

#Open file ('w' to overwrite if file exists) and print NIS macro text
with open(os.path.join(pathImageLib,nisMacrofile), 'w') as outputFile:
           outputFile.write('CloseAllDocuments(2);')
           outputFile.write(''+'\n')
           
           for df in os.listdir(pathImageLib):
       
               if fnmatch.fnmatch(df, '*cmle.ics'):
                   fileList.append(df)
                   #path converted to os compatible path using os.path.normpath
                   outputFile.write( 'OpenDocument("' + os.path.join(os.path.normpath(pathImageLib),df) + '",0);'+'\n')
                   outputFile.write('ActivateDocument("' + df + '");'+'\n')
                   outputFile.write('ConvertFloatToPic(0);'+'\n')
                   outputFile.write('ChangeChannelColor(0, 16711680);'+'\n')#Blue
                   outputFile.write('ChangeChannelColor(1, 65280);'+'\n')#Green
                   outputFile.write('ChangeChannelColor(2, 255);'+'\n')#Red
                   outputFile.write('ChangeChannelColor(3, 16777215);'+'\n') #White
                   outputFile.write('FlipVerticallyND(1,1,1);'+'\n')
                   outputFile.write('ImageSaveAs("' +os.path.join(os.path.normpath(pathImageLib),df[:-4])  + '.nd2",31,0);'+'\n')
                   outputFile.write('CloseAllDocuments(2);    '+'\n')
                   outputFile.write('\n')

#Output                   
print('The following NIS macro has been created: '+ nisMacrofile)
print('\tIt will process the following files:\n')
if len(fileList)!=0:
    for fileName in fileList: 
        print(fileName)
else:
    print('None') 
#Wait for keystroak so command prompt does not disappear            
input('\n'+str(os.path.basename(__file__))+' has terminated!! \n Press ENTER to exit....')
